<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PinteMod.ControlCenter.Core\PinteMod.ControlCenter.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="PinteMod.ControlCenter.Tests" />
  </ItemGroup>
</Project>
